xqemu/xqemu

build_windows.sh, configure, hw/xbox/nv2a/gloffscreen.c, hw/xbox/nv2a/nv2a.c, hw/xbox/nv2a/wglext.h
The implementation is nasty in places, but it should be fine for now.
Hardcoded opengl libs in the mingw32 code-path because setting opengl = 'yes' was unable to locate them & manually setting opengl_libs broke the build.
=> Fix build on Windows using msys2/mingw-w64

build_windows.sh
Build guide is also missing 2 packages that are needed for the 2.X rebase.
pacman -S mingw-w64-x86_64-SDL2 mingw-w64-x86_64-pixman
=> Fix build_windows.sh

build_linux.sh, build_macos.sh, build_windows.sh
This is done trough the pipefail option, that returns the first-nonzero
return value when programs are piped together.
This commit also succinctly comments the other options used.
I am not too happy with the amount of code duplication there. Couldn't the build options be saved somewhere else, or even in the same script which would autodetect the platform?
=> Build scripts: have them return the same error as make on failure

hw/xbox/nv2a/nv2a.c, hw/xbox/nv2a/nv2a.h, hw/xbox/nv2a/nv2a_pfifo.c
This patch adds an additional "retired" queue in which FIFO command
entry objects are placed after execution. This queue of objects is then
returned to the pusher's new "available" queue for re-use.
This improves the performance of the system by avoiding the costly
overhead associated with the general-purpose use of `malloc` and `free`
for previous allocation of FIFO command queue objects.
Resolves #54, but TBH performance improvement is *visibly* minor, compared to our other slowdowns (#50).
I think there is still a lot of room to optimize this puller/pusher setup. But this is pretty low-hanging fruit and provides good returns, so let's leave more architectural changes for another PR.
=> nv2a: Recycle FIFO command queue memory

Makefile, ui/sdl2.c
=> Window title "XQEMU [git hash]"

hw/xbox/Makefile.objs, hw/xbox/dsp/Makefile.objs
When I tried to use x86_64 linux in XQEMU (to debug input issues) I had trouble with SDL not being linked to XID-SDL. The fix in Makefile.objs solved that problem.
Also, the DSP code uses `SDL_GetTicks()` if `#ifdef DSP_COUNT_IPS` is true.
Probably because of that check, I did not get errors about dsp_cpu.o.
I still decided to add a "fix" for it.
Not sure if using the SDL timing code in the DSP is a good idea. QEMU has platform independent timers for various virtual and wall-clock-time situations. We should review this.
Purely as a note: The nv2a_pgraph code would *also* have some SDL dependency in the method handler for `NV097_FLIP_STALL`. However, that is in an `#if 0` block marked with `// HACK HACK HACK`. As that code is always disabled I did not add the SDL flags / lib there. …
=> Add SDL flags and libs to objects which use it

hw/xbox/nv2a/nv2a_int.h, hw/xbox/nv2a/nv2a_pgraph.c, hw/xbox/nv2a/nv2a_psh.c, hw/xbox/nv2a/nv2a_psh.h, hw/xbox/nv2a/nv2a_shaders.c, hw/xbox/nv2a/nv2a_shaders.h
Resolves #44
This PR adds partial support for window clipping. This fixes games which utilize clipping, such as Halo:CE which uses clipping in multiplayer to render multiple player screens.
Research and original PoC work done by Jannik Vogel:
- JayFoxRox/xqemu-espes@c05d91b
- JayFoxRox/xqemu-espes@a254830
This figure illustrates how (inclusive) clipping is performed with this PR, and how clipping region coordinates are transformed from D3D/NV2A coordinates to the OpenGL viewport coordinate system:
**Note:** this PR does not add complete clipping support. It will `assert` if "exclusive" clipping is used, and seems to have an off-by-1 issue most evident in Halo:CE with a new 1-pixel border along the top and right edges of the screen. However, these issues can be resolved after the PR is …
=> Add support for window clipping

configure
In the configure script, check if epoxy is installed. Fixes #67. Pretty bare-bones, but does the job.
=> Properly check for epoxy

get_deps.py
This fixes the Python script copying the DLLs by converting the Unix path to Windows paths. Apparently Python recognizes that it's running on Windows and thus interprets the paths wrong.
I was building on Drive D, and Python interpreted the path "/mingw64/bin/libgcc_s_seh-1.dll" as "D:/mingw64/bin/libgcc_s_seh-1.dll", which was wrong in my case.
This fixes #62.
=> Fix copying of DLLs on Windows

hw/xbox/lpc47m157.c, hw/xbox/nv2a/nv2a.c, hw/xbox/nv2a/nv2a.h, hw/xbox/nv2a/nv2a_pgraph.c, hw/xbox/nv2a/nv2a_prmcio.c, hw/xbox/nv2a/nv2a_prmvio.c, hw/xbox/nv2a/nv2a_pvideo.c, hw/xbox/nv2a/nv2a_stubs.c, hw/xbox/nvnet.c, hw/xbox/smbus_cx25871.c, hw/xbox/smbus_xbox_smc.c
This PR is to cleanup some of the Xbox-specific code, specifically.
- Removing dead code (Resolves #70)
- Eliminating some duplication through use of basic macros
- Ideally get all code passing through scripts/checkpatch.pl (I fixed some files during rebase, but there are more...)
- Additional cleanup tbd
Note: I'm not fixing up stuff we get from other places (e.g. wlgext.h), just our core Xbox stuff.
Many of our files are coming back clean now from checkpatch.pl. Still need to fixup:
- nv2a_pfifo.c
- nv2a_pgraph.c
- nv2a_shaders.c
checkpatch.pl will still complain about our usage of:
- `ERROR: use ctz32() instead of ffs()`
- C99 comment style (`// comment`)
- `#if 0`/`#endif` disabled code
- Lines with more than 80 characters
I've been using clang-format to do the extremely tedious bits, …
=> Perform some cleanup on Xbox code

build.sh
This is a very trivial change I've been meaning to perform for a while; this shouldn't have many significant drawbacks.
I'm doing this from the web interface, so you'll obviously need to wait for the CI, but it should be pretty harmless.
It performs a clean build in 18 seconds on my Ryzen 2700X, IIRC.
The commit message may lack a few words (as there are CPUs?), but I am a bit tired right now, and this seems understandable to me :smile:
=> build.sh: use as many threads as CPUs

build.sh
As noted in #106 this will produce working builds with GCC versions over 7.3.0-2. Upstream has already done this work-a-round.
=> Update configure with --disable-stack-protector

Makefile
Closes #93 .
This is a fix for the Makefile bug which led to AppVeyor builds showing the revision as dirty.
Reasoning for switching from `git diff-index` to `git diff` stems from how these two operate.
On a fresh cloned repo `git diff-index` has no local index to look at, it just sees fresh files and reports them as new. `git diff` on the other hand actually looks at the files and the upstream tree, finding that the files are unmodified copies downloaded from the repo. It reports no changes and updates the local index.
This updating behaviour leads to `git diff-index` being able to correctly identify unchanged files - this led to my first proposed solution of running `git diff` before running the "dirty-check".
=> ui: Stop appending "-dirty" to clean AppVeyor builds

hw/xbox/nv2a/nv2a.c, hw/xbox/nv2a/nv2a.h, hw/xbox/nv2a/nv2a_int.h, hw/xbox/nv2a/nv2a_pfifo.c, hw/xbox/nv2a/nv2a_pgraph.c, hw/xbox/nv2a/nv2a_user.c
This patch ports over the following commits by @espes from the XQEMU 1.x tree (available via tag archive-xqemu-1.x) to the refactored nv2a code:
- 4d9107e8 (HEAD -> xbox, upstream/xbox) Merge branch 'fix-fifo' into xbox
- c33f4ab2 cleanups
- d3f83d93 cleanups
- faca5dd0 fix
- 7c62d7c1 fixes
- 8ad239b0 wip
- 45ed3c31 wip
- c006d5e8 wip
=> nv2a FIFO Refactoring

hw/xbox/mcpx_apu.c, hw/xbox/nv2a/nv2a.c, hw/xbox/nv2a/nv2a_int.h, hw/xbox/nv2a/nv2a_pfifo.c
This replaces all ffs() calls in NV2A and MCPX with calls to ctz32() and adjusts the surrounding code. It also removes the ffs() implementation in NV2A provided for Windows.
The changes build and run fine under Arch Linux and Windows 7 (as far as I can tell).
Resolves #88.
=> Replace ffs() calls with ctz32()

hw/xbox/xbox.c, hw/xbox/xbox.h
Touches #28, but does not quite go the full distance.
Code is more or less @mborgerson's bootrom work, just refitted for this purpose.
What works:
=> Read EEPROM from file

hw/timer/mc146818rtc.c
Debug messages got turned on when porting over XBOX RTC changes. It's
quite noisy during startup, so keep them turned off by default.
=> rtc: Turn off debug messages

hw/xbox/nv2a/nv2a_int.h
Texture caching (enabled via USE_TEXTURE_CACHE macro) got turned off in
a cleanup commit (3d33d81). Turn it back on for performance.
=> nv2a: re-enable texture caching

hw/xbox/nv2a/nv2a_pgraph.c, hw/xbox/nv2a/nv2a_psh.c, hw/xbox/nv2a/nv2a_shaders.c
*I've originally intended to do more changes as part of a larger PR, but am splitting it into managable chunks now. This code has not been tested but it should work. Please test and review.*
This PR makes our c0 / c1 names more logical, and removes some dead-code. We had some variables which were only written, but never read.
I've also re-ordered texture/const-declaration and alpha-ref-logic code, because our order didn't make sense.
There should be no changes in observed behaviour.
=> Pixel shader cleanup

hw/xbox/nv2a/nv2a_pgraph.c
Our surface logic is really flawed.
In "Tony Hawk's American Wasteland" the game has data in buffer A [640x480], then it switches to buffer B [320x240], then buffer C [640x480], and then back to buffer A [640x480].
Our current code downloads (GL to RAM) the surface when going from A -> B (so A is up-to-date), it's not uploaded (RAM to GL) again when going from C -> A. So the GL buffer for A remains what was in the GL buffer for C. If we switch to another buffer now, A might be downloaded to RAM again, and will have completly wrong contents (GL buffer contents of C!).
That is because our current code only appears to check if the CPU has written a surface OR if the surface shape has changed before re-uploading. It doesn't even care if the address changed. The same issue exists for surface …
=> Force GL surface transfer on surface address or pitch changes

hw/xbox/nv2a/nv2a_pgraph.c
Fixes an off-by-one error in the window-clipping.
The lower right corner should be inclusive. So `x1 = x0 + 10` has to lead to a 11 pixel wide region (same deal with vertical size).
I did *not* test the exclusive mode, overlapping regions, anti-aliasing, surface clipping which might lead to overflows / underflows, and similar scenarios. This really *only* fixes an off-by-one.
The only other minor change I did was to change the type of involved variables to `unsigned int` because `pgraph_apply_anti_aliasing_factor` operates on `unsigned int*`, so using `GLuint` felt unsafe.
---
I tested this against a modified nxdk triangle sample, which contained the following code:
```c
/* Set up window-clipping region */
p = pb_begin();
pb_push1(p, NV097_SET_WINDOW_CLIP_TYPE, 0); p+=2;
for(i = 0; i < 8; …
```
=> nv2a: Fix window-clip region off-by-one error

appveyor.bat, appveyor.yml
This commit will enable appveyor to build both debug & release builds.
Builds are failing due to Python being updated in between `xqemu:master` and this commit. I've successfully built these changes on `gxtx:test` by disabling checking for Python updates in `appveyor.bat`.
Python was updated from `python2-2.7.15-2-x86_64` to `python2-2.7.15-3-x86_64`.
=> Add release builds to appveyor

hw/xbox/dsp/dsp_cpu.c, hw/xbox/dsp/dsp_emu.inl
Saw 'inc d' in some games GP FX or EP AC3 code once, so we will probably need it for audio emulation; also using it in DSP homebrew now. Adding 'dec d' was more of an afterthought for completeness.
I tested my implementation using https://github.com/JayFoxRox/xbox-tools/pull/70 (requires https://github.com/XboxDev/a56/pull/9).
I ran a couple of test cases to see how flags behave and if A / B register selection works. Everything seems to work fine, except readback issues which are likely caused by #148 and #149.
I did not implement the respective disassemblers yet (and don't intend to do so).
I didn't check for correctness of SR.S and SR.L bits, simply because they don't seem to be updated explicitly by most of our DSP code. These will have to be fixed in the future, if they are broken.
=>  dsp: Support 'inc d'  and 'dec d'

hw/xbox/mcpx_apu.c
**Use NV1BA0_PIO_VOICE_OFF_HANDLE mask**:
Should help with understanding the code
**Fix offset of scratch space PRD control word**:
If this code ever gets used, this should be correct now
**Activate voice on VOICE_ON, regardless of list position**:
I assume this was a bug in the code; the voice should probably always go active on VOICE_ON.
---
All of these changes come from https://github.com/JayFoxRox/xqemu-espes/pull/24
=> Address minor APU bugs

hw/xbox/mcpx_apu.c, hw/xbox/mcpx_apu.h, hw/xbox/xbox.c
This improves the APU memory access performance. This will be more important when we implement better DMA (possibly more data to transfer), VP (audio buffers must be loaded) and EP (FIFO must be read and written back).
Closes #156.
*I did not check for self-modifying PRDs (I don't think this is likely to happen, until we write our own crazy DSP homebrew).*
---
This has gotten very little testing. Please review my new logic for `scratch_rw`.
=> apu: Access system memory directly

README.md
As requested by JFR I've switched the place of the macOS and Linux CI badge titles.
=> docs: Use job-specific CI badges for macOS and Linux builds

hw/xbox/xid-sdl.c
The recent fixes to xid.c (32bf810) didn't make it to xid-sdl.c. This
patch ports over those changes. In the future, the parts common to both
xid.c and xid-sdl.c should be factored out so this doesn't happen again.
Original work done by Jannik Vogel (aka JayFoxRox) on Jul 5th, 2018.
=> xid: Port fixes made to xid.c to xid-sdl.c

hw/xbox/nv2a/nv2a_pgraph.c
Vertex attribute values provided via NV097_SET_VERTEX_DATA2S are
apparently two 16-bit signed integers, packed into 32 bits, which are
then to be directly mapped to floating point values in the range
[-32768.0, 32767.0].
Halo:CE uses this format to provide texture (u,v) coordinates for
render-to-texture techniques, including weapon scope, dynamic shadows,
and radar beacon--all of which are now working as expected with this
patch (*on branch [mborgerson:dev/halo](https://github.com/mborgerson/xqemu/tree/dev/halo), which allows for some additional 
unimplemented features which we will `assert` for on master branch*).
Fixes #165 
PartiallyFixes #119
=> nv2a: Fix NV097_SET_VERTEX_DATA2S scaling

hw/xbox/xid-sdl.c
Fixes xqemu/xqemu#182
Tested and the deadzone issue seems to be fixed in jJet Set Radio Future.
=> xid: Fix trigger range in xid-sdl

hw/xbox/dsp/dsp.c, hw/xbox/dsp/dsp.h, hw/xbox/dsp/dsp_dma.c, hw/xbox/dsp/dsp_dma.h, hw/xbox/mcpx_apu.c
This adds support for FIFO output in APU DSP DMA transfers. This is used during the boot-animation to send the audio output to AC97.
During normal operation (post boot-animation), this DMA to AC97 is handled by the EP (which we currently don't emulate). So in practice, we don't need FIFOs at the moment.
However, this lays the groundwork for circular scatter gather. This is used for buffer type 0xE (scratch space with circular addressing). Buffer 0xE is used to send output from the GP to the EP. Buffer 0xE is broken in the master revision (and not handled by this PR), but we can easily fix this in a follow-up PR.
I based my code on [the findings I've documented in XboxDevWiki](http://xboxdevwiki.net/DSP#Command_blocks).
The code in this PR has been tested against real hardware, and was …
=> Support FIFO output in DMA

build.sh, get_deps.py
Python 2.x is turning EOL at the end of the year. All of the QEMU scripts are already 3.X compatible the only thing not compatible is our `get_deps.py` for copying Windows DLL for redistribution which is also fixed in this PR.
I've not done extensive testing but everything builds and runs fine.
=> build.sh: Use Python 3.x for Windows

hw/xbox/nv2a/nv2a_pgraph.c
Not confirmed on hardware (and I don't intend to do so), but based on very strong assumptions and observed behavior.
Please test with a couple of games to confirm I didn't break anything.
This closes #119 and closes #36 for Battle Creek and Cartographer. It also solves Halo issues with the HUD.
*(This branch was rebased onto https://github.com/mborgerson/xqemu/tree/dev/halo for the screenshot)*
=> nv2a: Fix A8Y8 texture formats

hw/xbox/nv2a/nv2a_pgraph.c
This fixes #168 by memset()-ing the whole arrays and only copying the content of enabled register combiner stages.
=> nv2a: Set content of disabled register combiner stages to zero

hw/xbox/chihiro.c
Trying to run chihiro currently fails with `qemu-system-i386: Property '.mediaboard-rom' not found
`
As @JayFoxRox pointed out that's due to underscores '_' being kind of not allowed.
(They are replaced by hyphens '-' )
https://github.com/xqemu/xqemu/blob/960698a24ed7cd69fe2e452a28a3bb64e395a0fe/vl.c#L2706-L2711
=> chihiro: Fix property names by avoiding illegal symbols

hw/xbox/nv2a/nv2a_psh.c
[This should be closer to NV_register_combiners](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_register_combiners.txt).
I've had this code for a while and never bothered to fully test or PR it.
So this needs a bit of testing - but I assume it's correct.
=> psh: Use input mapping from NV_register_combiners GL extension

hw/xbox/nv2a/nv2a_psh.c
[This should be closer to NV_register_combiners](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_register_combiners.txt).
I've had this code for a while and never bothered to fully test or PR it.
So this needs a bit of testing - but I assume it's correct.
=> psh: Use output clamping from NV_register_combiners GL extension

hw/xbox/nv2a/nv2a_psh.c
Minor changes to our PSH code.
G should be an alpha component, as specified in [NV_register_combiners](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_register_combiners.txt):
> The variable G is an alpha scalar.
I've changed the types to make this safer, this includes the pseudo-registers:
> The alpha component of E_TIMES_F_NV and SPARE0_PLUS_SECONDARY_COLOR_NV is always zero.
There's still a lot of hacky code left, such as casts to `vec3`, so this *does not* solve #202, yet.
That will be solved in a more complicated follow-up.
---
I did only test this with the dashboard and Smashing Drive. The final version I'm sending as PR **already contains some last-minute fixups and was never tested**; I'll run tests during review.
**Should be tested with a handful of games to make sure …
=> Final combiner G input is a scalar

hw/xbox/mcpx_apu.c
This PR adds a small framework for implementing VP voice processing (which will happen in a future PR).
This framework includes VP &rarr; GP audio routing. Unfortunately this transfer is affected by #158 for 1024 words (32 channels * 32 samples).
For audio debugging purposes, this also adds a tone generator for injecting audio into the GP.
This tone isn't currently heard, because EP and ACI are severely broken (so audio isn't routed to speakers).
However, this tone will be useful in the future, to verify correct GP / EP behaviour, and can also be used to test audio-output without functional VP voice processing.
=> apu: Add VP framework

hw/xbox/nv2a/nv2a_pgraph.c
`NV097_SET_VERTEX_DATA2S` was fixed recently, but it still didn't specify a vertex when setting slot 0. I have now tested with "Conker - Live and Reloaded" and it runs into an assert for that.
I tested the following:
* Disabling the assert and removing the `pgraph_finish_inline_buffer_vertex` call, leads to another assert for `NV097_SET_BEGIN_END`.
* Disabling the assert and keeping `pgraph_finish_inline_buffer_vertex`, fixes the load-screens.
We had previously enabled `pgraph_finish_inline_buffer_vertex` for `NV097_SET_VERTEX_DATA` float types. However, this also seems to apply all other types. I believe it's this part in [NV_vertex_program](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_vertex_program.txt) (2.14.1.1  The Vertex Attribute Registers):
> Vertex program execution …
=> nv2a: Slot 0 of SET_VERTEX_DATA specifies a vertex

hw/xbox/nvnet.c
This is set by the running application, so the default value remains unused.
See https://github.com/LukeUsher/Cxbx-Reloaded/issues/15
=> nvnet: Guest MAC address should not be initialized by hardware

build.sh
Building GlusterFS support has been broken for a while now (at least on Arch, error log [here](https://pastebin.com/qfxdgUkh)).
xqemu doesn't require it anyway, so this disables GlusterFS in build.sh.
=> build.sh: Disable GlusterFS support

appveyor.bat
As stated in #221 the build script for appveyor wasn't completing the upgrade process for MSYS2 which caused a lib to become out of sync and not update. This PR fixes this by following the upgrade process recommended on MSYS2 website.
Fixes #221.
=> ci: Fix MSYS2 upgrade process for AppVeyor

appveyor.bat
#222 was supposed to fix #221 however it seems that during the time it took between the PR and merge MSYS2 updated *something* which broke building again. So from now on we wont update MSYS and let AppVeyor handle keeping packages up-to-date like we currently do with travis.
=> ci: Stop updating the MSYS2 platform on AppVeyor

.travis.yml
macOS has been broken for some time due to updated packages, we should be using what travis-ci gives us via similar scripts as to what we currently use for linux with the same provider.
I also updated the python version to 3.7, however I'm not sure this actually effects anything as both versions build fine.
=> ci: Fix compiling with macOS on travis-ci

build.sh
This attempts to use many unused or rarely used features.
I looked at the libraries that are linked to XQEMU and then tried to find the corresponding `configure` options.
I usually removed them if I believed there wouldn't be a performance impact, or that the feature isn't useful in the context of Xbox emulation.
There are *some* interesting features, which might be useful for some developers, and maybe even users. However, we don't currently provide documentation for those features, and they are niche use cases (like USB forwarding via network).
This was sloppily thrown together and I considered a draft PR, but we can fix issues during review.
Expect poor code quality and issues in the initial review phase.
---
In particular, this removes stuff like bluetooth support, virtualization …
=> build: Disable unused features

.travis.yml, build.sh
The problems we currently experience when building on macOS are caused by pkg-config not finding `libffi.pc`, which is a requirement for `pkg-config` to find `gobject-2.0`. libffi is not symlinked into `/usr/local` by homebrew on purpose, so we must add the path to `libffi.pc` to the `PKG_CONFIG_PATH` environment variable (this is the solution recommended by homebrew when installing libffi).
It seems that XQEMU doesn't actually require libffi when building, otherwise we'd have to add `/usr/local/opt/libffi/lib` to the libary search directories as well.
Building tested on macOS, building and running tested on Arch.
Closes #239.
=> Fix for building on macOS

hw/xbox/adpcm.h, hw/xbox/adpcm_block.h, hw/xbox/mcpx_apu.c
Note: This PR is part of a series of PRs coming to add basic audio.
---
This patch adds the code necessary to perform basic buffer sampling for
HW voices. Includes new register definitions, support for a few new
methods, envelope stepping, ADPCM decoding, and the individual voice
buffer sampling to be added to the VP output mixbufs. This code does not
add system audio playback nor streaming support.
[This code originates from Jannik Vogel's 2017 audio branch.](https://github.com/JayFoxRox/xqemu-espes/commits/audio) Copied into
the current, recently LGPL-licensed version of this file with
permission.
=> Audio PR #1: Import basic buffer sampling code

hw/xbox/smbus.h, hw/xbox/smbus_xbox_smc.c, hw/xbox/xbox.c, hw/xbox/xbox.h
This adds `avpack` parameter with options `scart`, `svideo`, `vga`, `rfu`, `hdtv`, `none`, and `composite` (by default).
Also improved constant definitions based on https://xboxdevwiki.net/AV_Cables.
=> smbus: Add feature to specify video output type

hw/xbox/nv2a/nv2a_pgraph.c, hw/xbox/nv2a/nv2a_regs.h
This implements the PGRAPH RDI.
RDI is an interface to access the RAM of PGRAPH. We might also PFB RDI in the future, but this is not implemented here.
On hardware, the GPU has to be idle before RDI can be used (apparently RDI shares some address lines with other GPU features). For now, this restriction will not be emulated in XQEMU. We can always make it more accurate in the future.
PGRAPH RDI is irrelevant for game emulation, because D3D drivers use it for features we probably don't need to emulate (optimization, debugging, ..). However, nv2a-trace will depend on this functionality, as some states can not be accessed through other interfaces.
I chose to silently ignore write, unless debug mode is used. The fact that D3D uses this prevents us from `assert(false)` on *writes*.
I chose to …
=> Support PGRAPH RDI

hw/xbox/nv2a/nv2a.c, hw/xbox/nv2a/nv2a_int.h, hw/xbox/nv2a/nv2a_pramdac.c, hw/xbox/nv2a/nv2a_regs.h
Closes #241 
This PR changes `nv2a_get_bpp`, so it also respects a RAMDAC configuration bit which decides wether to decode bits as X1R5G5B5 or R5G6B5.
The RAMDAC configuration bit was found using reverse engineering, but then [confirmed by matching code in the linux kernel](https://github.com/torvalds/linux/blob/851ca779d110f694b5d078bc4af06d3ad37169e8/drivers/gpu/drm/nouveau/dispnv04/crtc.c#L588-L589) (our old code only handled [this linux equivalent](https://github.com/torvalds/linux/blob/851ca779d110f694b5d078bc4af06d3ad37169e8/drivers/gpu/drm/nouveau/dispnv04/crtc.c#L574)).
A switch-case is now used to map modes from `CR[0x28]` to pseudo-magic bpp values for QEMU.
---
The resulting image will look fine:
Fixes Fable, and other games which use X1R5G5B5.
---
I was originally going to …
=> nv2a: Fix VGA get_bpp for X1R5G5B5

hw/xbox/lpc47m157.c
=> lpc: Fix typo in CONFIG_DEVICE_INTERRUPT constant

hw/xbox/nv2a/nv2a_int.h, hw/xbox/nv2a/nv2a_pramdac.c, hw/xbox/nv2a/nv2a_regs.h
They are needed to obtain current screen resolution.
=> nv2a: Add some missing RAMDAC registers

.travis.yml, build.sh
Small change to include `coreutils` in the macOS travis builds and use GNU compatible`greadlink` instead of `readlink` for the macOS platform.
closes https://github.com/xqemu/xqemu/issues/242
=> Update macOS build script to use GNU compatible greadlink

Makefile
`sh` evaluation of expressions is wonky.
`! expression` evaluates to the same as `expression` in `sh` which makes the dirty-check ineffective on some systems.
Tested locally on Debian Linux, works fine.
Would appreciate if someone could test the AppVeyor artifact on Windows and of course building it locally on both Windows and macOS.
=> build: Use bash

.github/workflows/build_macos.yml
Dependency resolution resulting in installation of 'python' will grab
python@3 which conflicts with existing python@2 installation's symlinks.
Unlink python@2 for now so python@3 can install cleanly.
This might break again in the future if GitHub's base image removes python@2, but should do the trick in the mean time. If it breaks for that reason, we can pull this line out.
=> ci: Unlink python@2 for macOS

hw/xbox/dsp/dsp_cpu.c
This change is enough to get the MS kernel to boot on big-endian PowerPC hardware. 
Execution reaches far enough for the nv2a emulation to hit glDrawRangeElements but unable to test further due to broken Mesa drivers. 
Cromwell does work.
=> dsp: fix running on big-endian PowerPC

.github/workflows/build_macos.yml
This fixes the CI builder for MacOS.
This is a change by mborgerson used in his XQEMU based project, unable to cherry-pick easily due to other changes so manually patched.
=>  ci: Remove glib from macOS dep list

hw/xbox/nv2a/nv2a_shaders.c
> Can confirm the previously untested sphere map texgen code in nv2a_shader.c works fine, ...
> Had to also fix assertions wrongly comparing against the texture stage index instead of the channel index.
As posted by @Voxel9 in mborgerson/xemu#13
=> nv2a: Enable fixed-function sphere map texgen
